
## Dependances
```{r dependancies, message=FALSE}
# Dépendances
library(XLConnect)
library(plyr)
library(dplyr)
library(tidyr)
library(rsunflo)
library(ggplot2)
```


## Plannification
### Création de plan d'expérience (WebSim)
```{r design_websim}
# Import des données
## Essais (n=2)
d <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="essais")
## Genotypes (n=3)
g <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="genotype")

# Plan factoriel complet
p <- expand.grid(carol=d$carol, genotype=g$genotype)
p <- p %>% join(d) %>% join(g)

# Ecriture au format websim
design(p, file="inst/doc/files/design_websim.xls", format="websim", user="casadebaig")
```

### Création du plan d'expérience (rsunflo)
```{r design_rsunflo}
# Import des données
## Essais (n=2)
d <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="essais")
## Genotypes (n=3)
g <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="genotype")

# Plan factoriel complet
p <- expand.grid(carol=d$carol, genotype=g$genotype)
p <- p %>% join(d) %>% join(g)

# Mise en forme au format rsunflo
DurationSoil = 5 # durée (j) de la période de simulation sans culture
design <- p %>% mutate(
  id = 1:dim(p)[1],
  begin = as.numeric(as.Date(begin)) + 2440588,
  end = as.numeric(as.Date(crop_harvest)) + 2440588 + DurationSoil,
  duration = end - begin,
  file = paste("DB/test/",carol,".txt",sep="")
)

# export design
saveRDS(design, "inst/doc/files/design.rds")
```



## Simulation

```{r simulation_rsunflo}
# Dependances
library(rvle)

# chargement du plan d'experience
design <- readRDS("inst/doc/files/design.rds")

# Modèle et plan
sunflo <- new("Rvle", file = "sunflo_web.vpz", pkg = "sunflo")
design_vle <- as.list(design)

# Paramétrisation par défaut
sunflo %>% run() %>% results() %>% shape(view="timed")

# Paramétrisation issue du plan d'expérience (1 unité de simulation)
sunflo %>% play(design_vle, unit=1) %>% shape(view="timed")

# Sortie graphique
sunflo %>% play(design_vle, unit=1) %>% shape(view="timed") %>% display()

# Multi-simulation du plan d'expérience (parallélisation possible : require(doMC), ?mlply)
model <- function(id){sunflo %>% play(design_vle, unit=match(id, design_vle$id)) %>% shape(view="timed")}

list_simulation <- design %>% select(id) 
output <- plyr::mlply(list_simulation, failwith(NULL, model))

# Agregation (1 unité -> une matrice)
output_timed <- output %>% compact() %>% ldply(.id="id")

# Calcul d'indicateurs (1 unité -> un vecteur)
output_indicators <- output %>% compact() %>% ldply(indicate, .id="id")
```


```{r simulation_debug, eval=FALSE}
library(rvle)

# Modèle et plan
sunflo <- new("Rvle", file = "sunflo_web.vpz", pkg = "sunflo")

# load reference simulation (SUNFLO v1.2, VLE 1.0.3)
load("inst/doc/files/output_ref.rdata")

# run current model
output_new <- sunflo %>% run() %>% results() %>% shape(view="timed")

# test
identical(output_ref, output_new)
```


## Analyse
```{r analysis, eval=FALSE}
# test model evaluation and visualization

data_test <- data_frame(
  model=c(rep(LETTERS[1:2],each=500)),
  simulated=rnorm(1000),
  observed=rnorm(1000)
)

data_test %>% group_by(model) %>% do(evaluate_error(.))

data_test %>% evaluate_plot(~ model, color="model")

data_test %>% evaluate_residuals(~ model, color="model")

```
