
## Dependances
```{r dependancies, message=FALSE}
# Dépendances
library(XLConnect)
library(plyr)
library(dplyr)
library(reshape2)
#library(tidyr)
library(rsunflo)
library(ggplot2)
```


## Plannification
### Création de plan d'expérience (WebSim)
```{r design_websim}
# Import des données
## Essais (n=2)
d <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="essais")
## Genotypes (n=3)
g <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="genotype")

# Plan factoriel complet
p <- expand.grid(carol=d$carol, genotype=g$genotype)
p <- p %>% join(d) %>% join(g)

# Ecriture au format websim
design(p, file="inst/doc/files/design_websim.xls", format="websim", user="casadebaig")
```

### Création du plan d'expérience (rsunflo)
```{r design_rsunflo}
# Import des données
## Essais (n=2)
d <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="essais")
## Genotypes (n=3)
g <- readWorksheetFromFile(file="inst/doc/files/design.xlsx", sheet="genotype")

# Plan factoriel complet
p <- expand.grid(carol=d$carol, genotype=g$genotype)
p <- p %>% join(d) %>% join(g)

# Mise en forme au format rsunflo
DurationSoil = 5 # durée (j) de la période de simulation sans culture
p <- mutate(
  p,
  id = 1:dim(p)[1],
  begin = as.numeric(as.Date(begin)) + 2440588,
  end = as.numeric(as.Date(crop_harvest)) + 2440588 + DurationSoil,
  duration = end - begin,
  file = paste("DB/test/",carol,".txt",sep="")
)
```



## Simulation
### Simulation avec le paquet rsunflo
```{r simulation_rsunflo}
# Dependances
library(rvle)

# Modèle et plan
sunflo <- new("Rvle", file = "sunflo_web.vpz", pkg = "sunflo")
design <- as.list(p)

# Paramétrisation par défaut
sunflo %>% run() %>% results() %>% shape(view="timed")

# Paramétrisation issue du plan d'expérience (1 unité de simulation)
sunflo %>% play(design, unit=1) %>% shape(view="timed")

# Sortie graphique
sunflo %>% play(design, unit=1) %>% shape(view="timed") %>% display()

# Multi-simulation du plan d'expérience (parallélisation possible : require(doMC), ?mlply)
model <- function(x){sunflo %>% play(design, unit=x) %>% shape(view="timed")}
output <- mlply(design$id, failwith(NULL, model))

# Agregation (1 unité -> une matrice)
output_timed <- output %>% compact() %>% ldply()

# Calcul d'indicateurs (1 unité -> un vecteur)
output_indicators <- output %>% compact() %>% ldply(indicate)
```

